// Généré depuis naruto_rabbit_names.csv – 528 noms
export const NARUTO_NAMES = [
  "A (Deuxième Raikage)",
  "A (Premier Raikage)",
  "A (Quatrième Raikage)",
  "A (Troisième Raikage)",
  "Abiru",
  "Ao",
  "Ajisaï",
  "Akaboshi",
  "Akamaru",
  "Akatsuchi",
  "Amaï",
  "Amachi",
  "Amaru",
  "Ame",
  "Ameno",
  "Ameyuri Ringo",
  "Ami",
  "Ancien des Hyûga",
  "Anko Mitarashi",
  "Aoba Yamashiro",
  "Aoi Rokushô",
  "Arashi",
  "Ashina Uzumaki",
  "Asuma Sarutobi",
  "Asura",
  "Atsui",
  "Ayame",
  "Baiu",
  "Baki",
  "Banna",
  "Baru Uchiwa",
  "Bekkô",
  "Benten",
  "Biwako Sarutobi",
  "Blue B",
  "Boruto Uzumaki",
  "Buna",
  "Bunpuku",
  "Burami",
  "Butsuma Senju",
  "Capitaine des Assassins de Suna",
  "Capitaine des ninjas du ciel",
  "Capitaine du vaisseau fantôme",
  "Chef des Tsuchigumo",
  "Chef du Clan Kaguya",
  "Chen",
  "Chen (étudiant)",
  "Chikushôdô (Premier)",
  "Chiriku",
  "Chiyo",
  "Chogo",
  "Chôji Akimichi",
  "Chôza Akimichi",
  "Chôchô Akimichi",
  "Chôjûrô",
  "Chômei",
  "Chûkaku",
  "Chûkichi",
  "Chûshin",
  "Commandant de l'Anbu",
  "Daï Maito",
  "Daibutsu",
  "Daichi",
  "Daikoku Funeno",
  "Daimaru",
  "Dajimu",
  "Dan Katô",
  "Dango",
  "Darui",
  "Danzô Shimura",
  "Deidara",
  "Dôtô Akimichi",
  "Dodaï",
  "Doki",
  "Dosu Kinuta",
  "Dotô Kazahana",
  "En",
  "Enma",
  "Ensui Nara",
  "Ebisu",
  "Ebizô",
  "En no Gyôja",
  "Fû",
  "Fû Yamanaka",
  "Fubuki Kakuyoku",
  "Fudô",
  "Fuen",
  "Fugaku Uchiwa",
  "Fugi",
  "Fuguki Suikazan",
  "Fûjin",
  "Fûka",
  "Fuki",
  "Furui",
  "Fusô",
  "Futaba",
  "Gaara",
  "Gaï Maito",
  "Gakidô",
  "Gaku Inuzuka",
  "Gamabunta",
  "Gamakichi",
  "Gamatatsu",
  "Ganryû",
  "Gantetsu (Iwa)",
  "Gantetsu",
  "Gatô",
  "Gari",
  "Gengetsu Hôzuki",
  "Genma Shiranui",
  "Gennô",
  "Gennaï",
  "Gen'yûmaru",
  "Giichi",
  "Ginji",
  "Ginkaku",
  "Gôza",
  "Gozu",
  "Gôzu",
  "Grand Chef Ninja de Kumo",
  "Guren",
  "Guruguru",
  "Gyûki",
  "Hagoromo Ôtsutsuki",
  "Haido",
  "Haku",
  "Han",
  "Hanzô",
  "Hana Inuzuka",
  "Hanabi Hyûga",
  "Hanzaki",
  "Hashirama Senju",
  "Hayama Shirakumo",
  "Hayase",
  "Hayate Gekkô",
  "Heiji",
  "Hiashi Hyûga",
  "Hibachi",
  "Hibari",
  "Hidan",
  "Hikaku Uchiwa",
  "Hikaru",
  "Himawari Uzumaki",
  "Hinata Hyûga",
  "Hinoe",
  "Hiruzen Sarutobi",
  "Hisame",
  "Hizashi Hyûga",
  "Hoheto Hyûga",
  "Hôichi",
  "Hôshô",
  "Hôki (Taki)",
  "Hôki (Takumi)",
  "Hôki (Watari)",
  "Homura Mitokado",
  "Hotaru",
  "Hotarubi",
  "Ibuse",
  "Ibushi",
  "Idate Morino",
  "Iggy",
  "Ikkaku Umino",
  "Inabi Uchiwa",
  "Inari",
  "Indra",
  "Ino Yamanaka",
  "Inoichi Yamanaka",
  "Ibiki Morino",
  "Inaho",
  "Inojin Yamanaka",
  "Iruka Umino",
  "Iô",
  "Iô (ninja médecin)",
  "Iroha Hyûga",
  "Isago",
  "Isaribi",
  "Ise",
  "Ishikawa",
  "Isobu",
  "Itachi Uchiwa",
  "Itama Senju",
  "Ittan",
  "Ittetsu",
  "Iwana Akame",
  "Iwashi Tatami",
  "Iyashi",
  "Izumo Kamizuki",
  "Izuna Uchiwa",
  "Jibachi",
  "Jiga",
  "Jigokudô",
  "Jigumo",
  "Jinin Akebino",
  "Jinpachi Munashi",
  "Jiraya",
  "Jiro",
  "Jirôbô",
  "Jôseki",
  "Jûbi",
  "Jûgo",
  "Junsai",
  "Kabuto Yakushi",
  "Kagami Uchiwa",
  "Kagari",
  "Kagerô",
  "Kaguya Ôtsutsuki",
  "Kaiza",
  "Kaji",
  "Kajika",
  "Kakashi Hatake",
  "Kakuzu",
  "Kamatari",
  "Kamikiri",
  "Kamira",
  "Kandachi",
  "Kankurô",
  "Kaori",
  "Karaï",
  "Karashi",
  "Karasu",
  "Karin",
  "Karui",
  "Kashike",
  "Kasumi",
  "Katsuyu",
  "Kawarama Senju",
  "Kazuma",
  "Kiba Inuzuka",
  "Kidomaru",
  "Kigiri",
  "Kihô",
  "Killer B",
  "Kimimaro",
  "Kin Tsuchi",
  "Kinkaku",
  "Kinoto",
  "Kiri (ninja)",
  "Kirisame",
  "Kisame Hoshigaki",
  "Kisuke Maboroshi",
  "Kitsuchi",
  "Kiyoi Yotsuki",
  "Kô Hyûga",
  "Kôji",
  "Kôji (Suna)",
  "Kôta",
  "Kohari Umino",
  "Koharu Utatane",
  "Kokuô",
  "Kokuyô",
  "Komachi",
  "Komaza",
  "Komugi",
  "Konan",
  "Konohamaru",
  "Korobi",
  "Kosuke Maruboshi",
  "Kotohime",
  "Kujaku",
  "Kumadori",
  "Kumade Toriichi",
  "Kotetsu Hagane",
  "Kurama",
  "Kurenaï Yûhi",
  "Kuroari",
  "Kurobachi",
  "Kuromaru",
  "Kurotsuchi",
  "Kushimaru Kuriarare",
  "Kushina Uzumaki",
  "Kyôya",
  "Kyodaigumo",
  "Kyûsuke",
  "Mabui",
  "Madara Uchiwa",
  "Mahiru",
  "Mai Kagetsu",
  "Maki",
  "Mamushi",
  "Manabu Akado",
  "Manda",
  "Manda II",
  "Mangetsu Hôzuki",
  "Matatabi",
  "Matsu",
  "Matsuri",
  "Matsuri (Konoha)",
  "Meizu",
  "Meï Terumî",
  "Menma",
  "Menma Uzumaki",
  "Mère de Chôji",
  "Mère de Hinata et Hanabi",
  "Mère d'Ino",
  "Midare",
  "Midori",
  "Mikoto Uchiwa",
  "Minato Namikaze",
  "Minoji",
  "Misumi Tsurugi",
  "Mito Uzumaki",
  "Mizore Fuyukuma",
  "Mizuki",
  "Mizunoe",
  "Moegi Kazamatsuri",
  "Mogusa",
  "Monga",
  "Monju",
  "Monzaemon Chikamatsu",
  "Motoï",
  "Mozuku",
  "Mû",
  "Mubi",
  "Mukade",
  "Murakumo Kurama",
  "Musaï",
  "Muta Aburame",
  "Nae",
  "Nadare Rôga",
  "Nagato",
  "Nagare",
  "Naka Uchiwa",
  "Nangô",
  "Naori Uchiwa",
  "Naruto Uzumaki",
  "Natsu",
  "Natsuhi",
  "Natsu Hyûga",
  "Nawaki",
  "Nekobaa",
  "Neji Hyûga",
  "Nejiri",
  "Nigaï",
  "Ningame",
  "Ningendô",
  "Nishi",
  "Nobori",
  "Nonô Yakushi",
  "Nurari",
  "Obito Uchiwa",
  "Oboro",
  "Ôkei",
  "Okisuke",
  "Omoï",
  "Orochimaru",
  "Osoï",
  "Otokaze",
  "Ôtora",
  "Oyone",
  "Pakkun",
  "Pakura",
  "Partenaire de Sekiei",
  "Rai Uchiwa",
  "Raidô Namiashi",
  "Raïga Kurosuki",
  "Raijin",
  "Ran",
  "Ranka",
  "Ranmaru",
  "Rasa",
  "Reki",
  "Renga",
  "Riichi",
  "Riichi (ninja)",
  "Rin Nohara",
  "Rinji",
  "Rock Lee",
  "Rôshi",
  "Ruiga",
  "Ruka",
  "Ryôkan",
  "Ryûgan",
  "Ryûsa",
  "Ryûsui",
  "Sabiru",
  "Saï",
  "Sagan",
  "Saiken",
  "Sajin",
  "Sajô",
  "Samui",
  "Samo",
  "Sana",
  "Santa Yamanaka",
  "Sakon et Ukon",
  "Sakumo Hatake",
  "Sakura Haruno",
  "Sanshô",
  "Sanshôuo",
  "Sari",
  "Sarada Uchiwa",
  "Sasori",
  "Sasame",
  "Sasuke Uchiwa",
  "Satetsu",
  "Saya",
  "Seimei",
  "Sekiei",
  "Sekka",
  "Sen",
  "Sensei de Kabuto",
  "Setsuna Uchiwa",
  "Shamon",
  "Shiba",
  "Shiba (Kusa)",
  "Shibi Aburame",
  "Shibire",
  "Shibuki",
  "Shiho",
  "Shigure",
  "Shijimi",
  "Shikadai Nara",
  "Shikaku Nara",
  "Shikuro Aburame",
  "Shikamaru Nara",
  "Shima",
  "Shimeji",
  "Shimon Hijiri",
  "Shin",
  "Shinju",
  "Shinku Yûhi",
  "Shin Uchiwa",
  "Shinnô",
  "Shino Aburame",
  "Shinobu Mibu",
  "Shiore",
  "Shira",
  "Shiranami",
  "Shishio",
  "Shisui Uchiwa",
  "Shizune",
  "Shôseki",
  "Shun",
  "Shukaku",
  "Shura",
  "Shuradô",
  "Son Gokû",
  "Sôsetsu Kazahana",
  "Sora",
  "Suien",
  "Suigetsu Hôzuki",
  "Suika",
  "Suiko",
  "Suiren",
  "Suiren (Kiri)",
  "Suzume",
  "Suzumebachi",
  "Sumaru",
  "Sukima",
  "Sukui",
  "Sukune",
  "Suname",
  "Taiseki",
  "Taji",
  "Tajiki",
  "Taku",
  "Tango",
  "Tanzô",
  "Tatewaki",
  "Tatsuji",
  "Tayuya",
  "Tazuna",
  "Tekka Uchiwa",
  "Tekuno Kanden",
  "Temari",
  "Temui",
  "Tenga",
  "Tenten",
  "Terai",
  "Tetsu",
  "Teuchi",
  "Teyaki Uchiwa",
  "Tobi",
  "Tobio",
  "Tobirama Senju",
  "Tonbo Tobitake",
  "Tôka Senju",
  "Tokara Aburame",
  "Toki",
  "Tokuma Hyûga",
  "Tomari",
  "Torifu Akimichi",
  "Toroï",
  "Torune Aburame",
  "Towa",
  "Tsubaki",
  "Tsubusa",
  "Tsuchino",
  "Tsume Inuzuka",
  "Tsunade",
  "Tsunami",
  "Tsurugi",
  "Tsuzumi Sarugaku",
  "Udon",
  "Umibôzu",
  "Uruchi Uchiwa",
  "Uroko Kurama",
  "Utakata",
  "Waraji",
  "Watase",
  "Yagura Karatachi",
  "Yagura (anime)",
  "Yajirobee",
  "Yahiko",
  "Yokaze",
  "Yakku",
  "Yakumi Uchiwa",
  "Yakumo Kurama",
  "Yamame",
  "Yamato",
  "Yaoki",
  "Yashiro Uchiwa",
  "Yome",
  "Yoroï Akadô",
  "Yoshino Nara",
  "Yota",
  "Yotaka",
  "Yûgao Uzuki",
  "Yugito Nii",
  "Yukata",
  "Yûdachi",
  "Yûkimaru",
  "Yûra",
  "Zabuza Momochi",
  "Zaji",
  "Zaku Abumi",
  "Zetsu",
  "Zôri",
];
